import { categoryLabel, subcategoryLabel } from './categoryLabels';

export const NEW: string[] = [];

export const UPDATED: string[] = [];

export type Subcategory = {
	slug: string;
	label: string;
};

export type Category = {
	slug: string;
	label: string;
	subcategories: Subcategory[];
};

/** @deprecated Prefer `category.slug` / `subcategory.slug`. Kept for legacy call sites. */
export const slug = (s: string) => s.replace(/\s+/g, '-').toLowerCase();

function sub(key: string): Subcategory {
	return { slug: slug(key), label: subcategoryLabel(key) };
}

function cat(key: string, keys: string[]): Category {
	return { slug: slug(key), label: categoryLabel(key), subcategories: keys.map(sub) };
}

export const CATEGORIES: Category[] = [
	cat('Get Started', ['Introduction', 'Installation', 'MCP Server', 'Index']),
	cat('Text Animations', [
		'Split Text',
		'Blur Text',
		'Circular Text',
		'Text Type',
		'Shuffle',
		'Shiny Text',
		'Text Pressure',
		'Curved Loop',
		'Fuzzy Text',
		'Gradient Text',
		'Falling Text',
		'Text Cursor',
		'Decrypted Text',
		'True Focus',
		'Scroll Float',
		'Scroll Reveal',
		'ASCII Text',
		'Scrambled Text',
		'Rotating Text',
		'Glitch Text',
		'Scroll Velocity',
		'Variable Proximity',
		'Count Up'
	]),
	cat('Animations', [
		'Animated Content',
		'Fade Content',
		'Electric Border',
		'Orbit Images',
		'Pixel Transition',
		'Glare Hover',
		'Antigravity',
		'Logo Loop',
		'Target Cursor',
		'Magic Rings',
		'Laser Flow',
		'Magnet Lines',
		'Ghost Cursor',
		'Gradual Blur',
		'Click Spark',
		'Magnet',
		'Sticker Peel',
		'Pixel Trail',
		'Cubes',
		'Metallic Paint',
		'Noise',
		'Shape Blur',
		'Crosshair',
		'Image Trail',
		'Ribbons',
		'Splash Cursor',
		'Meta Balls',
		'Blob Cursor',
		'Star Border'
	]),
	cat('Components', [
		'Animated List',
		'Scroll Stack',
		'Bubble Menu',
		'Magic Bento',
		'Circular Gallery',
		'Reflective Card',
		'Card Nav',
		'Card Nav v2',
		'Stack',
		'Pill Nav',
		'Tilted Card',
		'Masonry',
		'Glass Surface',
		'Dome Gallery',
		'Chroma Grid',
		'Folder',
		'Staggered Menu',
		'Model Viewer',
		'Profile Card',
		'Dock',
		'Gooey Nav',
		'Pixel Card',
		'Carousel',
		'Spotlight Card',
		'Border Glow',
		'Flying Posters',
		'Card Swap',
		'Glass Icons',
		'Decay Card',
		'Flowing Menu',
		'Elastic Slider',
		'Counter',
		'Infinite Menu',
		'Stepper',
		'Bounce Cards'
	]),
	cat('Backgrounds', [
		'Liquid Ether',
		'Prism',
		'Dark Veil',
		'Light Pillar',
		'Silk',
		'Floating Lines',
		'Light Rays',
		'Pixel Blast',
		'Color Bends',
		'Evil Eye',
		'Line Waves',
		'Radar',
		'Soft Aurora',
		'Aurora',
		'Plasma',
		'Plasma Wave',
		'Particles',
		'Gradient Blinds',
		'Grainient',
		'Grid Scan',
		'Beams',
		'Pixel Snow',
		'Lightning',
		'Prismatic Burst',
		'Galaxy',
		'Dither',
		'Faulty Terminal',
		'Ripple Grid',
		'Dot Field',
		'Dot Grid',
		'Threads',
		'Hyperspeed',
		'Iridescence',
		'Waves',
		'Grid Distortion',
		'Ballpit',
		'Orb',
		'Letter Glitch',
		'Grid Motion',
		'Shape Grid',
		'Liquid Chrome',
		'Balatro'
	])
];

export const decodeLabel = (subSlug: string): string => {
	for (const category of CATEGORIES) {
		const match = category.subcategories.find((item) => item.slug === subSlug);
		if (match) return match.label;
	}
	return subSlug
		.split('-')
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(' ');
};

export const IMPLEMENTED_DEMOS = new Set<string>([
	'introduction',
	'installation',
	'mcp-server',
	'index',
	'shiny-text',
	'split-text',
	'scroll-float',
	'animated-content',
	'dock',
	'aurora',
	'balatro',
	'iridescence',
	'silk',
	'threads',
	'plasma',
	'liquid-chrome',
	'lightning',
	'dark-veil',
	'ripple-grid',
	'light-rays',
	'letter-glitch',
	'particles',
	'radar',
	'soft-aurora',
	'grid-motion',
	'plasma-wave',
	'grainient',
	'line-waves',
	'evil-eye',
	'grid-distortion',
	'dot-grid',
	'orb',
	'galaxy',
	'pixel-snow',
	'gradient-blinds',
	'waves',
	'floating-lines',
	'prism',
	'prismatic-burst',
	'light-pillar',
	'dither',
	'pixel-blast',
	'shape-grid',
	'magic-rings',
	'gradient-text',
	'glitch-text',
	'star-border',
	'splash-cursor',
	'noise',
	'blur-text',
	'fade-content',
	'dot-field',
	'color-bends',
	'liquid-ether',
	'faulty-terminal',
	'hyperspeed',
	'flying-posters',
	'true-focus',
	'falling-text',
	'count-up',
	'beams',
	'ballpit',
	'grid-scan',
	'click-spark',
	'magnet',
	'magnet-lines',
	'glare-hover',
	'gradual-blur',
	'crosshair',
	'blob-cursor',
	'cubes',
	'logo-loop',
	'orbit-images',
	'pixel-transition',
	'target-cursor',
	'ghost-cursor',
	'sticker-peel',
	'electric-border',
	'antigravity',
	'pixel-trail',
	'ribbons',
	'shape-blur',
	'meta-balls',
	'laser-flow',
	'metallic-paint',
	'image-trail',
	'animated-list',
	'border-glow',
	'bounce-cards',
	'bubble-menu',
	'card-nav',
	'card-nav-v2',
	'card-swap',
	'carousel',
	'chroma-grid',
	'counter',
	'decay-card',
	'elastic-slider',
	'flowing-menu',
	'folder',
	'glass-icons',
	'gooey-nav',
	'spotlight-card',
	'tilted-card',
	'reflective-card',
	'stack',
	'masonry',
	'pixel-card',
	'stepper',
	'scroll-stack',
	'pill-nav',
	'staggered-menu',
	'profile-card',
	'magic-bento',
	'glass-surface',
	'circular-gallery',
	'dome-gallery',
	'infinite-menu',
	'model-viewer',
	'text-cursor',
	'scrambled-text',
	'circular-text',
	'text-type',
	'shuffle',
	'text-pressure',
	'curved-loop',
	'fuzzy-text',
	'decrypted-text',
	'rotating-text',
	'scroll-reveal',
	'ascii-text',
	'variable-proximity',
	'scroll-velocity'
]);

export const isImplemented = (sub: Subcategory | string): boolean => {
	const key = typeof sub === 'string' ? sub : sub.slug;
	return IMPLEMENTED_DEMOS.has(key);
};

export const GET_STARTED_SLUG = 'get-started';
