/** Russian display labels for docs categories and components (URL slugs stay English). */
const CATEGORY: Record<string, string> = {
	'Get Started': 'Начало работы',
	'Text Animations': 'Анимация текста',
	Animations: 'Анимации',
	Components: 'Компоненты',
	Backgrounds: 'Фоны'
};

const SUBCATEGORY: Record<string, string> = {
	Introduction: 'Введение',
	Installation: 'Установка',
	'MCP Server': 'MCP-сервер',
	Index: 'Каталог',
	'Split Text': 'Разделённый текст',
	'Blur Text': 'Размытый текст',
	'Circular Text': 'Круговой текст',
	'Text Type': 'Эффект печати',
	Shuffle: 'Перемешивание',
	'Shiny Text': 'Блестящий текст',
	'Text Pressure': 'Давление текста',
	'Curved Loop': 'Изогнутый цикл',
	'Fuzzy Text': 'Нечёткий текст',
	'Gradient Text': 'Градиентный текст',
	'Falling Text': 'Падающий текст',
	'Text Cursor': 'Текстовый курсор',
	'Decrypted Text': 'Расшифровка',
	'True Focus': 'Фокус',
	'Scroll Float': 'Плавающий скролл',
	'Scroll Reveal': 'Появление при скролле',
	'ASCII Text': 'ASCII-текст',
	'Scrambling ASCII': 'Scrambling ASCII',
	'Scrambled Text': 'Перемешанный текст',
	'Rotating Text': 'Вращающийся текст',
	'Glitch Text': 'Глитч-текст',
	'Scroll Velocity': 'Скорость скролла',
	'Variable Proximity': 'Близость символов',
	'Count Up': 'Счётчик',
	'Animated Content': 'Анимированный контент',
	'Fade Content': 'Плавное появление',
	'Electric Border': 'Электрическая рамка',
	'Orbit Images': 'Орбитальные изображения',
	'Pixel Transition': 'Пиксельный переход',
	'Glare Hover': 'Блик при наведении',
	Antigravity: 'Антигравитация',
	'Logo Loop': 'Зацикленный логотип',
	'Target Cursor': 'Целевой курсор',
	'Magic Rings': 'Магические кольца',
	'Laser Flow': 'Лазерный поток',
	'Magnet Lines': 'Магнитные линии',
	'Ghost Cursor': 'Призрачный курсор',
	'Gradual Blur': 'Постепенное размытие',
	'Click Spark': 'Искра при клике',
	Magnet: 'Магнит',
	'Sticker Peel': 'Отклеивающаяся наклейка',
	'Pixel Trail': 'Пиксельный след',
	Cubes: 'Кубы',
	'Metallic Paint': 'Металлическая краска',
	Noise: 'Шум',
	'Shape Blur': 'Размытие формы',
	Crosshair: 'Прицел',
	'Image Trail': 'След изображений',
	Ribbons: 'Ленты',
	'Splash Cursor': 'Курсор-брызги',
	'Meta Balls': 'Мета-шары',
	'Blob Cursor': 'Курсор-капля',
	'Star Border': 'Звёздная рамка',
	'Animated List': 'Анимированный список',
	'Scroll Stack': 'Стек при скролле',
	'Bubble Menu': 'Пузырьковое меню',
	'Magic Bento': 'Magic Bento',
	'Circular Gallery': 'Круговая галерея',
	'Reflective Card': 'Отражающая карточка',
	'Card Nav': 'Навигация карточками',
	'Card Nav v2': 'Навигация карточками v2',
	Stack: 'Стек',
	'Pill Nav': 'Пилюльная навигация',
	'Draggable Pill Nav': 'Перетаскиваемая пилюльная навигация',
	'Tilted Card': 'Наклонённая карточка',
	Masonry: 'Мозаика',
	'Glass Surface': 'Стеклянная поверхность',
	'Dome Gallery': 'Купольная галерея',
	'Chroma Grid': 'Хроматическая сетка',
	Folder: 'Папка',
	'Staggered Menu': 'Ступенчатое меню',
	'Model Viewer': 'Просмотр 3D-моделей',
	'Profile Card': 'Карточка профиля',
	Dock: 'Док',
	Button: 'Кнопка',
	'Gooey Nav': 'Gooey Nav',
	'Pixel Card': 'Пиксельная карточка',
	Carousel: 'Карусель',
	'Cinematic Slider': 'Cinematic 3D слайдер',
	'Distortion Slider': 'Distortion слайдер',
	'Spotlight Card': 'Карточка с подсветкой',
	'Border Glow': 'Светящаяся рамка',
	'Flying Posters': 'Летающие постеры',
	'Card Swap': 'Обмен карточками',
	'Glass Icons': 'Стеклянные иконки',
	'Decay Card': 'Разрушающаяся карточка',
	'Flowing Menu': 'Текучее меню',
	'Elastic Slider': 'Эластичный слайдер',
	Counter: 'Счётчик',
	'Infinite Menu': 'Бесконечное меню',
	Stepper: 'Степпер',
	'Bounce Cards': 'Прыгающие карточки',
	'Liquid Ether': 'Жидкий эфир',
	Prism: 'Призма',
	'Dark Veil': 'Тёмная вуаль',
	'Light Pillar': 'Световой столп',
	Silk: 'Шёлк',
	'Floating Lines': 'Парящие линии',
	'Light Rays': 'Лучи света',
	'Pixel Blast': 'Пиксельный взрыв',
	'Color Bends': 'Цветовые изгибы',
	'Evil Eye': 'Злое око',
	'Line Waves': 'Волны линий',
	Radar: 'Радар',
	'Soft Aurora': 'Мягкая аврора',
	Aurora: 'Аврора',
	Plasma: 'Плазма',
	'Plasma Wave': 'Плазменная волна',
	Particles: 'Частицы',
	'Gradient Blinds': 'Градиентные жалюзи',
	Grainient: 'Grainient',
	'Grid Scan': 'Сканирование сетки',
	Beams: 'Лучи',
	'Pixel Snow': 'Пиксельный снег',
	Lightning: 'Молния',
	'Prismatic Burst': 'Призматический взрыв',
	Galaxy: 'Галактика',
	Dither: 'Дизеринг',
	'Faulty Terminal': 'Сбойный терминал',
	'Ripple Grid': 'Рябящая сетка',
	'Dot Field': 'Поле точек',
	'Dot Grid': 'Сетка точек',
	Threads: 'Нити',
	Hyperspeed: 'Сверхскорость',
	Iridescence: 'Переливы',
	Waves: 'Волны',
	'Grid Distortion': 'Искажение сетки',
	Ballpit: 'Шарики',
	Orb: 'Сфера',
	'Letter Glitch': 'Глитч букв',
	'Grid Motion': 'Движение сетки',
	'Shape Grid': 'Форменная сетка',
	'Liquid Chrome': 'Жидкий хром',
	Balatro: 'Balatro'
};

export function categoryLabel(key: string): string {
	return CATEGORY[key] ?? key;
}

export function subcategoryLabel(key: string): string {
	return SUBCATEGORY[key] ?? key;
}
